# Generated by Django 3.2.22 on 2023-11-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
