# Generated by Django 3.2.22 on 2023-12-03 14:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20231125_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tip_percentage',
            field=models.DecimalField(choices=[(Decimal('0'), 'No tip'), (Decimal('0.05'), '5%'), (Decimal('0.10'), '10%'), (Decimal('0.15'), '15%')], decimal_places=2, default=0, max_digits=5),
        ),
    ]
