# Generated by Django 3.2.22 on 2023-12-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_remove_order_tip_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='total_tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
