# Generated by Django 3.2.22 on 2023-12-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20231204_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='tip_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
