# Generated by Django 3.2.22 on 2023-12-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20231204_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_tip',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='tip_amount',
        ),
    ]
