# Generated by Django 3.2.22 on 2023-12-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_order_discount1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount1',
        ),
    ]
