# Generated by Django 3.2.22 on 2023-12-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_remove_order_discount1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
